name: "Basic Node App"
description: "My first real add-on!"
version: "1.0.1"
slug: "basic_node_app"
init: false
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
host_network: true
ports:
  3000/tcp: 3000