name: "Basic Node App"
description: "My first real add-on!"
version: "1.0.0"
slug: "basic_node_app"
init: false
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
build_from:
  amd64: "node:22"
  armhf: "node:22"
  armv7: "node:22"
  aarch64: "node:22"
  i386: "node:22"